# Generated by Django 5.0.4 on 2024-05-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_historicallotteryticket_alter_lotteryticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallotteryticket',
            name='draw_id',
            field=models.BigIntegerField(unique=True, verbose_name='Draw ID'),
        ),
    ]
