# Generated by Django 5.0.4 on 2024-05-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_historicallotteryticket_draw_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallotteryticket',
            name='draw_date',
            field=models.DateField(unique=True, verbose_name='Draw Date'),
        ),
        migrations.AlterField(
            model_name='lotteryticket',
            name='purchase_date',
            field=models.DateField(),
        ),
    ]
